/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./src/components/form/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JText: typeof import('./src/components/J-Text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
